wafer/sponsors/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from wafer.sponsors.views import (
    ShowSponsors, SponsorView, ShowPackages, SponsorViewSet, PackageViewSet)


router = routers.DefaultRouter()
router.register(r'sponsors', SponsorViewSet)
router.register(r'packages', PackageViewSet)

urlpatterns = [
    url(r'^$', ShowSponsors.as_view(),
        name='wafer_sponsors'),
    url(r'^(?P<pk>\d+)/$', SponsorView.as_view(), name='wafer_sponsor'),
    url(r'^packages/$', ShowPackages.as_view(),
        name='wafer_sponsorship_packages'),
    url(r'^api/', include(router.urls)),
]

wafer/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^accounts/', include('wafer.registration.urls')),
    url(r'^users/', include('wafer.users.urls')),
    url(r'^talks/', include('wafer.talks.urls')),
    url(r'^sponsors/', include('wafer.sponsors.urls')),
    url(r'^pages/', include('wafer.pages.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^markitup/', include('markitup.urls')),
    url(r'^schedule/', include('wafer.schedule.urls')),
    url(r'^tickets/', include('wafer.tickets.urls')),
    url(r'^kv/', include('wafer.kv.urls')),
]

# Serve media
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pages occupy the entire URL space, and must come last
urlpatterns.append(url(r'', include('wafer.pages.urls')))

wafer/sponsors/models.py
# -*- coding: utf-8 -*-

import logging

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from markitup.fields import MarkupField

from wafer.menu import menu_logger, refresh_menu_cache

logger = logging.getLogger(__name__)


@python_2_unicode_compatible
class File(models.Model):
    """A file for use in sponsor and sponshorship package descriptions."""
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    item = models.FileField(upload_to='sponsors_files')

    def __str__(self):
        return u'%s (%s)' % (self.name, self.item.url)


@python_2_unicode_compatible
class SponsorshipPackage(models.Model):
    """A description of a sponsorship package."""
    order = models.IntegerField(default=1)
    name = models.CharField(max_length=255)
    number_available = models.IntegerField(
        null=True, validators=[MinValueValidator(0)])
    currency = models.CharField(
        max_length=16, default='$',
        help_text=_("Currency symbol for the sponsorship amount."))
    price = models.DecimalField(
        max_digits=12, decimal_places=2,
        help_text=_("Amount to be sponsored."))
    short_description = models.TextField(
        help_text=_("One sentence overview of the package."))
    description = MarkupField(
        help_text=_("Describe what the package gives the sponsor."))
    files = models.ManyToManyField(
        File, related_name="packages", blank=True,
        help_text=_("Images and other files for use in"
                    " the description markdown field."))
    # We use purely ascii help text, to avoid issues with the migrations
    # not handling unicode help text nicely.
    symbol = models.CharField(
        max_length=1, blank=True,
        help_text=_("Optional symbol to display in the sponsors list "
                    "next to sponsors who have sponsored at this list, "
                    "(for example *)."))

    class Meta:
        ordering = ['order', '-price', 'name']

    def __str__(self):
        return u'%s (amount: %.0f)' % (self.name, self.price)

    def number_claimed(self):
        return self.sponsors.count()


@python_2_unicode_compatible
class Sponsor(models.Model):
    """A conference sponsor."""
    order = models.IntegerField(default=1)
    name = models.CharField(max_length=255)
    packages = models.ManyToManyField(SponsorshipPackage,
                                      related_name="sponsors")
    description = MarkupField(
        help_text=_("Write some nice things about the sponsor."))
    files = models.ManyToManyField(
        File, related_name="sponsors", blank=True,
        help_text=_("Images and other files for use in"
                    " the description markdown field."))
    url = models.URLField(
        default="", blank=True,
        help_text=_("Url to link back to the sponsor if required"))

    class Meta:
        ordering = ['order', 'name', 'id']

    def __str__(self):
        return u'%s' % (self.name,)

    def get_absolute_url(self):
        return reverse('wafer_sponsor', args=(self.pk,))

    def symbols(self):
        """Return a string of the symbols of all the packages this sponsor has
           taken."""
        packages = self.packages.all()
        symbols = u"".join(p.symbol for p in packages)
        return symbols

    @property
    def logo(self):
        return self.files.get(name='logo').item

    @property
    def symbol(self):
        """The symbol of the highest level package this sponsor has taken."""
        package = self.packages.first()
        if package:
            return package.symbol
        return u""


def sponsor_menu(
        root_menu, menu="sponsors", label=_("Sponsors"),
        sponsors_item=_("Our sponsors"),
        packages_item=_("Sponsorship packages")):
    """Add sponsor menu links."""
    root_menu.add_menu(menu, label, items=[])
    for sponsor in (
            Sponsor.objects.all()
            .order_by('packages', 'order', 'id')
            .prefetch_related('packages')):
        symbols = sponsor.symbols()
        if symbols:
            item_name = u"» %s %s" % (sponsor.name, symbols)
        else:
            item_name = u"» %s" % (sponsor.name,)
        with menu_logger(logger, "sponsor %r" % (sponsor.name,)):
            root_menu.add_item(
                item_name, sponsor.get_absolute_url(), menu=menu)

    if sponsors_item:
        with menu_logger(logger, "sponsors page link"):
            root_menu.add_item(
                sponsors_item, reverse("wafer_sponsors"), menu)
    if packages_item:
        with menu_logger(logger, "sponsorship package page link"):
            root_menu.add_item(
                packages_item, reverse("wafer_sponsorship_packages"), menu)


post_save.connect(refresh_menu_cache, sender=Sponsor)

wafer/sponsors/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView

from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissionsOrAnonReadOnly

from wafer.sponsors.models import Sponsor, SponsorshipPackage
from wafer.sponsors.serializers import SponsorSerializer, PackageSerializer


class ShowSponsors(ListView):
    template_name = 'wafer.sponsors/sponsors.html'
    model = Sponsor

    def get_queryset(self):
        return Sponsor.objects.all().order_by('packages', 'order', 'id')


class SponsorView(DetailView):
    template_name = 'wafer.sponsors/sponsor.html'
    model = Sponsor


class ShowPackages(ListView):
    template_name = 'wafer.sponsors/packages.html'
    model = SponsorshipPackage


class SponsorViewSet(viewsets.ModelViewSet):
    """API endpoint for users."""
    queryset = Sponsor.objects.all()
    serializer_class = SponsorSerializer
    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )


class PackageViewSet(viewsets.ModelViewSet):
    """API endpoint for users."""
    queryset = SponsorshipPackage.objects.all()
    serializer_class = PackageSerializer
    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )

wafer/sponsors/templates/wafer.sponsors/packages.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% block content %}
<section class="wafer wafer-sponsorship-packages">
<h1>{% trans 'Sponsorship Packages' %}</h1>
<div class="wafer list">
    {% for package in sponsorshippackage_list %}
    <section class="wafer wafer-sponsorship-package">
    <div>
        <h2>{{ package.name }} ({{ package.currency }} {{ package.price|floatformat:0 }})</h1>
        {% if package.number_available %}
            <p>{% trans 'Total number available:' %} {{ package.number_available }}</p>
        {% endif %}
        <p>{% trans 'Packages claimed:' %} {{ package.number_claimed }}</p>

        {% if package.symbol %}
            <p>Symbol shown in the sponsor list: {{ package.symbol }}</p>
        {% endif %}

        <p>{{ package.short_description }}</p>
        {{ package.description.rendered|safe }}
    </div>
    </section>
    {% empty %}
    <p>No sponsorship packages available yet.</p>
    {% endfor %}
</div>
</section>
{% endblock %}

wafer/sponsors/templates/wafer.sponsors/sponsor.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% block content %}
<section class="wafer wafer-sponsor">
<h1>
   {% if object.url %}
   <a href="{{ object.url }}">{{ object.name }}</a>
   {% else %}
   {{ object.name }}
   {% endif %}
</h1>
<div class="sponsor-detail">
{{ object.description.rendered|safe }}
</div>
</section>
{% endblock %}

wafer/sponsors/templates/wafer.sponsors/sponsors.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% block title %}{% trans "Sponsors" %} - {{ WAFER_CONFERENCE_NAME }}{% endblock %}
{% block content %}
<section class="wafer wafer-sponsors">
  <h1>{% trans 'Sponsors' %}</h1>
  <div class="wafer list">
    {% for sponsor in sponsor_list %}
      <section class="wafer wafer-sponsor
                      wafer-sponsor-{{ sponsor.packages.first.name.lower }}">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">
             {% if sponsor.symbol %}
               {{ sponsor.symbol }}
             {% endif %}
             {% if sponsor.url %}
               <a href="{{ sponsor.url }}">{{ sponsor.name }}</a>
             {% else %}
               {{ sponsor.name }}
             {% endif %}
             <small class="text-right">{{ sponsor.packages.first.name }}</small>
            </h2>
            {{ sponsor.description.rendered|safe }}
          </div>
        </div>
        <hr>
      </section>
    {% empty %}
      <p>No sponsors yet.</p>
    {% endfor %}
  </div>
</section>
{% endblock %}

wafer/sponsors/templates/wafer.sponsors/sponsors_block.html
{% load sponsors %}
<div id="wafer-sponsors">
    {% for package in packages %}
    {% if package.sponsors.exists %}
        <div>
            <div class="package">{{ package.name }}</div>
            <ul>
                {% for sponsor in package.sponsors.all %}
                    <li>
                        {% sponsor_image_url sponsor "logo" as logo_url %}
                        {% if logo_url != '' %}
                            <img src="{{ logo_url }}"
                                 alt="{{ sponsor.name }}"
                                 title="{{ sponsor.name }}">
                        {% else %}
                            <span class="nologo">{{ sponsor.name }}</span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% endfor %}
</div>